// Maps a backend team/country name (game.team1_name / team2_name — free-form
// strings like "Brazil", "Argentina", "South Korea") to an ISO 3166-1 alpha-2
// code, which addresses the flag assets in src/icons/fiats (named by alpha-2).
//
// The backend gives only a display name — there is no country code or flag
// reference on the wire — so this client-side lookup is the bridge. Keys are
// lowercased; lookup is case-insensitive and trims. Extend freely as new
// competitions/teams appear; an unknown name falls through to a placeholder.

const NAME_TO_ALPHA2: Record<string, string> = {
  // — Full members most likely to appear in fixtures —
  brazil: "BR",
  argentina: "AR",
  france: "FR",
  england: "GB", // no separate England flag asset; GB (Union Jack) is the closest
  netherlands: "NL",
  holland: "NL",
  germany: "DE",
  croatia: "HR",
  colombia: "CO",
  morocco: "MA",
  spain: "ES",
  portugal: "PT",
  italy: "IT",
  belgium: "BE",
  uruguay: "UY",
  mexico: "MX",
  myanmar: "MM",
  "united states": "US",
  usa: "US",
  canada: "CA",
  japan: "JP",
  "south korea": "KR",
  "korea republic": "KR",
  australia: "AU",
  poland: "PL",
  switzerland: "CH",
  denmark: "DK",
  sweden: "SE",
  norway: "NO",
  serbia: "RS",
  senegal: "SN",
  ghana: "GH",
  nigeria: "NG",
  cameroon: "CM",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  tunisia: "TN",
  algeria: "DZ",
  egypt: "EG",
  ecuador: "EC",
  peru: "PE",
  chile: "CL",
  paraguay: "PY",
  "costa rica": "CR",
  panama: "PA",
  honduras: "HN",
  jamaica: "JM",
  "saudi arabia": "SA",
  qatar: "QA",
  iran: "IR",
  iraq: "IQ",
  "united arab emirates": "AE",
  turkey: "TR",
  "turkiye": "TR",
  greece: "GR",
  austria: "AT",
  "czech republic": "CZ",
  czechia: "CZ",
  hungary: "HU",
  romania: "RO",
  ukraine: "UA",
  russia: "RU",
  scotland: "GB",
  wales: "GB",
  ireland: "IE",
  "republic of ireland": "IE",
  "northern ireland": "GB",
  iceland: "IS",
  finland: "FI",
  slovakia: "SK",
  slovenia: "SI",
  "bosnia and herzegovina": "BA",
  "north macedonia": "MK",
  albania: "AL",
  bulgaria: "BG",
  "new zealand": "NZ",
  "south africa": "ZA",
  "cape verde": "CV",
  mali: "ML",
  "burkina faso": "BF",
  "dr congo": "CD",
  "democratic republic of the congo": "CD",
  angola: "AO",
  "south sudan": "SS",
  "china": "CN",
  "china pr": "CN",
  india: "IN",
  indonesia: "ID",
  thailand: "TH",
  vietnam: "VN",
  bolivia: "BO",
  venezuela: "VE",
  "trinidad and tobago": "TT",
};

/** Team/country display name → ISO 3166-1 alpha-2 code, or undefined if unknown. */
export function countryNameToAlpha2(name: string | null | undefined): string | undefined {
  if (!name) return undefined;
  return NAME_TO_ALPHA2[name.trim().toLowerCase()];
}
