import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * The `game_event` push message: mirrors the `game_event` columns a client
 * needs to render a live heartbeat. The full raw feed message is
 * deliberately omitted here — it is unbounded in size and exists for
 * replay integrity; clients that need it use the REST event-log route
 * (`GET /games/:game_id/events`) instead.
 */
export class GameEventMessageDto {
  @ApiProperty({
    format: 'uuid',
    example: '00000000-0000-4000-8000-000000000001',
  })
  id: string;

  @ApiProperty({ type: 'integer', example: 3 })
  game_id: number;

  @ApiProperty({
    example: 'attack_possession',
    description: 'Feed Action — an open set, not an enum.',
  })
  type: string;

  @ApiPropertyOptional({
    type: 'integer',
    nullable: true,
    example: 42,
    description: 'Feed Id — matches confirm/amend/discard actions.',
  })
  action_id: number | null;

  @ApiProperty({
    type: 'integer',
    example: 7,
    description: 'Feed Seq, per-fixture monotonic ordering.',
  })
  seq: number;

  @ApiPropertyOptional({
    nullable: true,
    example: null,
    description: 'Feed Confirmed — goals: false first, ~80s median to true.',
  })
  confirmed: boolean | null;

  @ApiPropertyOptional({
    type: 'integer',
    nullable: true,
    example: 1,
    description: '1 | 2',
  })
  participant: number | null;

  @ApiPropertyOptional({
    type: 'integer',
    nullable: true,
    example: 4,
    description: 'Raw feed StatusId — open set, not an enum.',
  })
  status_id: number | null;

  @ApiProperty({
    example: '2026-07-18T15:12:03.000Z',
    description: 'Feed Ts.',
  })
  feed_ts: string;

  @ApiProperty({
    example: true,
    description:
      'Always true this phase — generated by a synthetic timer, not derived from a real match feed. Phase 5 removes this property when real data lands.',
  })
  is_mock: boolean;
}
