import { ApiProperty } from '@nestjs/swagger';
import { QuestionResponseDto } from '../../api/games/dto/question-response.dto';

/**
 * The `question` push message. Reuses `QuestionResponseDto` (the REST games
 * module's prediction-card contract, embedding exactly four options whose
 * `base_gain` values are the LOCKED 5/7/15/100 ladder) rather than declaring
 * a parallel shape, so the REST and WS views of a question cannot drift
 * apart. Adds only `is_mock` on top.
 */
export class QuestionMessageDto extends QuestionResponseDto {
  @ApiProperty({
    example: true,
    description:
      'Always true this phase — generated by a synthetic timer, not derived from a real match feed. Phase 5 removes this property when real data lands.',
  })
  is_mock: boolean;
}
