import { ApiProperty } from '@nestjs/swagger';

/**
 * The `resolution` push message: emitted ~5s after the `question` message
 * carrying the same `game_question_id`, per D-03. `resolved_option_id` is
 * always one of the four option ids the correlated question carried.
 */
export class ResolutionMessageDto {
  @ApiProperty({
    format: 'uuid',
    example: '00000000-0000-4000-8000-0000000000f1',
    description: 'Correlates this resolution to the question it resolves.',
  })
  game_question_id: string;

  @ApiProperty({
    format: 'uuid',
    example: '00000000-0000-4000-8000-000000000104',
    description: 'One of the four option ids carried by the resolved question.',
  })
  resolved_option_id: string;

  @ApiProperty({
    example: 'goal',
    enum: ['fizzles', 'danger', 'shot', 'goal'],
  })
  resolved_outcome_key: string;

  @ApiProperty({
    type: 'integer',
    enum: [5, 7, 15, 100],
    example: 15,
    description:
      "The resolved option's own frozen base_gain — the LOCKED, calibrated point value awarded.",
  })
  awarded_points: number;

  @ApiProperty({ example: true })
  successful_outcome: boolean;

  @ApiProperty({ example: '2026-07-18T15:12:08.000Z' })
  resolved_at: string;

  @ApiProperty({
    example: true,
    description:
      'Always true this phase — generated by a synthetic timer, not derived from a real match feed. Phase 5 removes this property when real data lands.',
  })
  is_mock: boolean;
}
