import { ApiProperty } from '@nestjs/swagger';
import { MatchClockDto } from './match-clock.dto';
import { QuestionResponseDto } from '../../api/games/dto/question-response.dto';

/**
 * The `snapshot` event: emitted to a client immediately on `subscribe`,
 * mirroring the real in-memory `GameState` plus the D-07 match clock.
 * `active_question` reuses `QuestionResponseDto` from the REST games module
 * (rather than redeclaring the shape) so the two surfaces of a question can
 * never drift apart. The key is always present — a snapshot delivered
 * before any fake question has fired sets it to `null` explicitly, never an
 * empty object and never an omitted key (WS-02).
 */
export class SnapshotDto {
  @ApiProperty({ type: 'integer', example: 3 })
  game_id: number;

  @ApiProperty({
    type: 'integer',
    example: 1,
    description: 'Mirrors game.score_p1 — sourced from GameState.score1.',
  })
  score_p1: number;

  @ApiProperty({
    type: 'integer',
    example: 0,
    description: 'Mirrors game.score_p2 — sourced from GameState.score2.',
  })
  score_p2: number;

  @ApiProperty({
    example: 'AttackPossession',
    enum: [
      'SafePossession',
      'AttackPossession',
      'DangerPossession',
      'HighDangerPossession',
    ],
    nullable: true,
    description: 'Sourced from GameState.possessionStage.',
  })
  possession_stage: string | null;

  @ApiProperty({ type: () => MatchClockDto, description: 'D-07 match clock.' })
  clock: MatchClockDto;

  @ApiProperty({
    type: () => QuestionResponseDto,
    nullable: true,
    description:
      'The currently open question, or null when no question has fired yet. Always present as a key, even when null.',
  })
  active_question: QuestionResponseDto | null;

  @ApiProperty({
    example: true,
    description:
      'Always true this phase — generated by a synthetic timer, not derived from a real match feed. Phase 5 removes this property when real data lands.',
  })
  is_mock: boolean;
}
